version: 2
jobs:
  build_kind:
    docker:
      - image: circleci/golang:1.16
    steps:
      - run: wget https://github.com/kubernetes-sigs/kind/releases/download/v0.11.1/kind-linux-amd64
      - run: mkdir -p workspace/bin
      - run: cp kind-linux-amd64 workspace/bin/kind
      - run: chmod +x workspace/bin/kind
      - persist_to_workspace:
          root: workspace
          paths:
            - bin
  build_e2e:
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/k8s.io/kubernetes
    steps:
      - run: git clone https://github.com/kubernetes/kubernetes.git .
      - run:
          name: Prepare environment
          command: |
            mkdir -p workspace/bin
            curl -L https://dl.k8s.io/v1.22.2/kubernetes-test-linux-amd64.tar.gz -o ./kubernetes-test-linux-amd64.tar.gz
            curl -L https://dl.k8s.io/v1.22.2/bin/linux/amd64/kubectl -o workspace/bin/kubectl
      - run:
          name: share binaries
          command: |
            tar xvzf ./kubernetes-test-linux-amd64.tar.gz \
              --directory workspace/bin
              --strip-components=3 kubernetes/test/bin/ginkgo kubernetes/test/bin/e2e.test

      - persist_to_workspace:
          root: workspace
          paths:
            - bin
  build:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01
    working_directory: ~/go/src/github.com/aojea/kindnet
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Create kindnet image
          command: |
            TAG="test" ./build.sh 
            mkdir /tmp/workspace/docker
            docker save -o /tmp/workspace/docker/kindnet.tar aojea/kindnetd:test
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - docker

  e2e_ptp:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01
    working_directory: ~/go/src/github.com/aojea/kindnet
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Install dependencies
          command: |
            chmod +x /tmp/workspace/bin/*
            sudo cp /tmp/workspace/bin/* /usr/local/bin/
      - run:
          name: Create kind cluster
          command: |
            KUBECONFIG="${HOME}/.kube/kind-test-config"
            export KUBECONFIG
            kind create cluster --image aojea/kindnode:latest --config .circleci/config-ipv4-ci.yaml --loglevel debug --wait 1m
            kind load image-archive /tmp/workspace/docker/kindnet.tar
            sed -i 's/aojea\/kindnetd/aojea\/kindnetd:test/' install-kindnet.yaml
            kubectl apply -f install-kindnet.yaml
            kubectl wait --timeout=90s -n kube-system --for=condition=Ready -l k8s-app=kube-dns pods
            kubectl get nodes -o wide
            kubectl get pods --all-namespaces -o wide
            kubectl get services --all-namespaces -o wide
      - run:
          name: Run e2e tests
          no_output_timeout: 200m
          command: |
            # setting this env prevents ginkgo e2e from trying to run provider setup
            export KUBECONFIG="${HOME}/.kube/kind-test-config"
            export KUBERNETES_CONFORMANCE_TEST='y'
            e2e.test --provider=skeleton --context kind-kind --ginkgo.focus "Networking.*Conformance" --num-nodes 2

  e2e_bridge:
    machine:
      enabled: true
      image: ubuntu-2004:202010-01
    working_directory: ~/go/src/github.com/aojea/kindnet
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run:
          name: Install dependencies
          command: |
            chmod +x /tmp/workspace/bin/*
            sudo cp /tmp/workspace/bin/* /usr/local/bin/
      - run:
          name: Create kind cluster
          command: |
            KUBECONFIG="${HOME}/.kube/kind-test-config"
            export KUBECONFIG
            kind create cluster --image aojea/kindnode:latest --config .circleci/config-ipv4-ci.yaml --loglevel debug --wait 1m
            kind load image-archive /tmp/workspace/docker/kindnet.tar
            sed -i 's/aojea\/kindnetd/aojea\/kindnetd:test/' install-kindnet-bridge.yaml
            kubectl apply -f install-kindnet.yaml
            kubectl wait --timeout=90s -n kube-system --for=condition=Ready -l k8s-app=kube-dns pods
            kubectl get nodes -o wide
            kubectl get pods --all-namespaces -o wide
            kubectl get services --all-namespaces -o wide
      - run:
          name: Run e2e tests
          no_output_timeout: 200m
          command: |
            # setting this env prevents ginkgo e2e from trying to run provider setup
            export KUBECONFIG="${HOME}/.kube/kind-test-config"
            export KUBERNETES_CONFORMANCE_TEST='y'
            e2e.test --provider=skeleton --context kind-kind --ginkgo.focus "Networking.*Conformance" --num-nodes 2

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_kind
      - build_e2e
      - build
      - e2e_ptp:
          requires:
            - build
            - build_e2e
            - build_kind
      - e2e_bridge:
          requires:
            - build
            - build_e2e
            - build_kind

